#!/bin/sh

function usage {
	echo "Usage: profilerrific [-h|--help] -s <script>* [-r <revision>*] [-g <graphing script>]"
}

function tidy {
	echo "$@" | sed -e 's/\s*-.*//'
}

if [[ ! "$*" ]]; then
	usage;
	exit
fi

while [[ "$@" ]]; do
	ARG="$1"
	shift
	case "$ARG" in
	-h|--help)      usage; break;;
	-r|--revisions) revisions=`tidy "$@"`;;
	-s|--scripts)   scripts=`  tidy "$@"`;;
	-g|--grapher)   grapher=`  tidy "$@"`;;
	esac
done

echo "Revisions: $revisions"
echo "Scripts:   $scripts"

for revision in $revisions; do
	git checkout -- $revision
	for script in $scripts; do
		$script
	done
done

if [[ ! "$revisions" ]]; then
	for script in $scripts; do
		$script
	done
fi

if [[ "$grapher" ]]; then
	for revisionl in $revisions; do
		for revisionr in $revisions; do
			if [[ $revisionl -lt $revisionr ]]; then
				for script in $scripts; do
					echo "Graphing script $script results for revisions $revisionl vs. $revisionr"
					$grapher $script $revisionl $revisionr
				done
			fi
		done
	done
fi
